# Generated by Django 2.0.9 on 2019-01-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190104_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference_code',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
