# Generated by Django 2.0.9 on 2019-01-04 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='purchasestatus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='purchasestatus',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='provider',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasestatus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasestatus',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
