# Generated by Django 2.0.9 on 2019-01-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='city',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='country',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='region',
            name='modified_date',
        ),
    ]
