# Generated by Django 2.0.9 on 2019-01-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=21, max_digits=20),
            preserve_default=False,
        ),
    ]
